on: push

name: package-usage-tests

defaults:
 run:
  working-directory: ./tests/end2end/app/

jobs:
  main:
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    runs-on: ${{ matrix.config.os }}

    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        config:
        - {os: macOS-latest,   r: 'release'}
        - {os: windows-latest, r: 'release'}
        - {os: ubuntu-22.04, r: 'devel'}
        - {os: ubuntu-22.04, r: 'release'}
        - {os: ubuntu-22.04, r: 'oldrel'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: local::. # Necessary to avoid object usage linter errors.

      - name: Install shiny.benchmark
        run: |
          Rscript -e "install.packages('remotes')"
          Rscript -e "remotes::install_local('../../../', quiet = TRUE)"

      - name: Create app structure
        run: |
          bash ./../setting_branches.sh

      - name: Check basic functionality - Cypress
        run: |
          Rscript ../run_tests.R cypress master,develop tests/cypress/ use_this_one_1 FALSE 1

      - name: Check basic functionality - shinytest2
        run: |
          Rscript ../run_tests.R shinytest2 master,develop tests/ use_this_one_1 FALSE 1

      - name: Check if it fails when renv not present - Cypress
        run: |
          Rscript ./../run_tests.R cypress renv_missing,renv_shiny1,renv_shiny2 tests/cypress/ use_this_one_1 FALSE 1

      - name: Check if it fails when renv not present - shinytest2
        run: |
          Rscript ./../run_tests.R shinytest2 renv_missing,renv_shiny1,renv_shiny2 tests/ use_this_one_1 FALSE 1

      - name: Check if it can handle renv - Cypress
        run: |
          Rscript ./../run_tests.R cypress renv_missing,renv_shiny1,renv_shiny2 tests/cypress/ use_this_one_1 TRUE 1

      - name: Check if it can handle renv - shinytest2
        run: |
          Rscript ./../run_tests.R shinytest2 renv_missing,renv_shiny1,renv_shiny2 tests/ use_this_one_1 TRUE 1

      - name: Check if it can handle multiple files - Cypress
        run: |
          Rscript ./../run_tests.R cypress renv_shiny1,renv_shiny2 tests/cypress/,fake_folder/tests/cypress/ use_this_one_1 TRUE 1

      - name: Check if it can handle multiple files - shinytest2
        run: |
          Rscript ./../run_tests.R shinytest2 renv_shiny1,renv_shiny2 tests/,fake_folder/tests/ use_this_one_1 TRUE 1

      - name: Check if we can replicate tests - Cypress
        run: |
          Rscript ./../run_tests.R cypress master,develop tests/cypress/ use_this_one_1 FALSE 2

      - name: Check if we can replicate tests - shinytest2
        run: |
          Rscript ./../run_tests.R shinytest2 master,develop tests/ use_this_one_1 FALSE 2

      - name: Check if we can run tests based on file patterns - Cypress
        run: |
          Rscript ./../run_tests.R cypress master,develop tests/cypress/ use_this_one_[0-9] FALSE 1

      - name: Check if we can run tests based on file patterns - shinytest2
        run: |
          Rscript ./../run_tests.R shinytest2 master,develop tests/ use_this_one_[0-9] FALSE 1
