on: push

name: package-usage-tests

defaults:
 run:
  working-directory: ./.github/workflows/tests/app

jobs:
  main:
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    runs-on: ${{ matrix.config.os }}

    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        config:
        - {os: ubuntu-22.04, r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: local::. # Necessary to avoid object usage linter errors.

      - name: Create app structure
        run: |
          bash ./../setting_branches.sh

      - name: Install shiny.performance
        run: |
          R CMD build ../../../../.
          R CMD INSTALL shiny.performance_0.1.1.tar.gz

      - name: Check basic functionality
        run: |
          Rscript ./../run_tests.R cypress master,develop app/tests/cypress_tests1.js FALSE

      - name: Check if it fails when renv not present
        run: |
          Rscript ./../run_tests.R cypress renv_missing,renv_shiny1,shiny2 app/tests/cypress_tests1.js FALSE

      - name: Check if it can handle renv
        run: |
          Rscript ./../run_tests.R cypress renv_missing,renv_shiny1,shiny2 app/tests/cypress_tests1.js TRUE
