on: push

name: package-usage-tests

defaults:
 run:
  working-directory: ./.github/workflows/tests/app

jobs:
  main:
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    runs-on: ${{ matrix.config.os }}

    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        config:
        - {os: ubuntu-22.04, r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: local::. # Necessary to avoid object usage linter errors.

      - name: Create app structure
        run: |
          bash ./../setting_branches.sh

      - name: Install shiny.performance
        run: |
          R -e "install.packages('remotes')"
          R -e "remotes::install_github(repo = 'Appsilon/experimental.performance', auth_token = Sys.getenv('GITHUB_PAT'), ref = 'develop', quiet = TRUE)"

      - name: Check basic functionality - Cypress
        run: |
          Rscript ./../run_tests.R cypress master,develop ../cypress_tests1.js FALSE

      - name: Check basic functionality - shinytest2
        run: |
          Rscript ./../run_tests.R shinytest2 master,develop tests/ FALSE

      - name: Check if it fails when renv not present - Cypress
        run: |
          Rscript ./../run_tests.R cypress renv_missing,renv_shiny1,renv_shiny2 ../cypress_tests1.js FALSE

      - name: Check if it fails when renv not present - shinytest2
        run: |
          Rscript ./../run_tests.R shinytest2 renv_missing,renv_shiny1,renv_shiny2 tests FALSE

      - name: Check if it can handle renv - Cypress
        run: |
          Rscript ./../run_tests.R cypress renv_missing,renv_shiny1,renv_shiny2 ../cypress_tests1.js TRUE

      - name: Check if it can handle renv - shinytest2
        run: |
          Rscript ./../run_tests.R shinytest2 renv_missing,renv_shiny1,renv_shiny2 tests TRUE

      - name: Check if it can handle multiple files - Cypress
        run: |
          Rscript ./../run_tests.R cypress renv_shiny1,renv_shiny2 ../cypress_tests1.js,../cypress_tests2.js TRUE

      - name: Check if it can handle multiple files - shinytest2
        run: |
          Rscript ./../run_tests.R shinytest2 renv_shiny1,renv_shiny2 tests,fake_folder/tests TRUE

